### ISSUE TITLE
This guy is surrounded by too much time

### ISSUE THREAD

**Issue by TimoA200** [satoqz/dhbw-typst-template#1]

**Comment by satoqz** [comment]
You too can have lots of time if you simply cut out the two biggest distractions in your life:
1. Food
2. Sleep

Trust me

**Comment by TimoA200** [comment]
Bro Im eating right now, what should I do?

**Comment by satoqz** [comment]
It's too late for you then - your only remaining way to reach success in life is investing into crypto

**Comment by TimoA200** [comment]
Okay, what coin?

**Comment by satoqz** [comment]
[cheapETH](https://cheapeth.org/) is probably the way to go
